export const LANGUAGE_CONTEXTS = {
  en: {
    'lang': 'en',
    'lang_en': true,
    'lang_site_name': 'navilan',
    'lang_site_title': 'reasonably unfiltered',
    'lang_about_name': 'about',
    'lang_writings_name': 'writings',
    'lang_read_more': 'Read',
    'lang_nav_back_to_writings': 'Back to writings',
    'lang_nav_previous_post': 'Previous Post',
    'lang_nav_next_post': 'Next Post',
    'lang_posts_count': 'posts',
    'lang_search': 'Search',
    'lang_previous': 'Previous',
    'lang_next': 'Next',
    'lang_page': 'Page',
    'lang_of': 'of',
    'lang_total_posts': 'total posts'
  },
  ta: {
    'lang': 'ta',
    'lang_ta': true,
    'lang_site_name': 'நவிலன்',
    'lang_site_title': 'எண்ணக்கூவல்',
    'lang_about_name': 'இவன்',
    'lang_writings_name': 'எழுத்து',
    'lang_read_more': 'திற',
    'lang_nav_back_to_writings': 'பதிவுகள்',
    'lang_nav_previous_post': 'முந்தய பதிவு',
    'lang_nav_next_post': 'அடுத்த பதிவு',
    'lang_posts_count': 'பதிவுகள்',
    'lang_search': 'தேடு',
    'lang_previous': 'பின்னே',
    'lang_next': 'முன்னே',
    'lang_page': 'பக்கம்',
    'lang_of': '/',
    'lang_total_posts': 'பக்கங்கள்'
  }
} as const;