# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "accepts-1.3.8" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.8.tgz";
        sha512 = "PYAthTa2m2VKxuvSD3DPC/Gy+U+sOA1LAuT8mkmRuvw+NACSaeXEQ+NHcVF7rONl6qcaxV3Uuemwawk+7+SJLw==";
      };
    };
    "anymatch-2.0.0" = {
      name = "anymatch";
      packageName = "anymatch";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/anymatch/-/anymatch-2.0.0.tgz";
        sha512 = "5teOsQWABXHHBFP9y3skS5P3d/WfWXpv3FUpy+LorMrNYaT9pI4oLMQX7jzQ2KklNpGpWHzdCXTDT2Y3XGlZBw==";
      };
    };
    "apache-crypt-1.2.6" = {
      name = "apache-crypt";
      packageName = "apache-crypt";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/apache-crypt/-/apache-crypt-1.2.6.tgz";
        sha512 = "072WetlM4blL8PREJVeY+WHiUh1R5VNt2HfceGS8aKqttPHcmqE5pkKuXPz/ULmJOFkc8Hw3kfKl6vy7Qka6DA==";
      };
    };
    "apache-md5-1.1.8" = {
      name = "apache-md5";
      packageName = "apache-md5";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/apache-md5/-/apache-md5-1.1.8.tgz";
        sha512 = "FCAJojipPn0bXjuEpjOOOMN8FZDkxfWWp4JGN9mifU2IhxvKyXZYqpzPHdnTSUpmPDy+tsslB6Z1g+Vg6nVbYA==";
      };
    };
    "arr-diff-4.0.0" = {
      name = "arr-diff";
      packageName = "arr-diff";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-diff/-/arr-diff-4.0.0.tgz";
        sha512 = "YVIQ82gZPGBebQV/a8dar4AitzCQs0jjXwMPZllpXMaGjXPYVUawSxQrRsjhjupyVxEvbHgUmIhKVlND+j02kA==";
      };
    };
    "arr-flatten-1.1.0" = {
      name = "arr-flatten";
      packageName = "arr-flatten";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-flatten/-/arr-flatten-1.1.0.tgz";
        sha512 = "L3hKV5R/p5o81R7O02IGnwpDmkp6E982XhtbuwSe3O4qOtMMMtodicASA1Cny2U+aCXcNpml+m4dPsvsJ3jatg==";
      };
    };
    "arr-union-3.1.0" = {
      name = "arr-union";
      packageName = "arr-union";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/arr-union/-/arr-union-3.1.0.tgz";
        sha512 = "sKpyeERZ02v1FeCZT8lrfJq5u6goHCtpTAzPwJYe7c8SPFOboNjNg1vz2L4VTn9T4PQxEx13TbXLmYUcS6Ug7Q==";
      };
    };
    "array-unique-0.3.2" = {
      name = "array-unique";
      packageName = "array-unique";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-unique/-/array-unique-0.3.2.tgz";
        sha512 = "SleRWjh9JUud2wH1hPs9rZBZ33H6T9HOiL0uwGnGx9FpE6wKGyfWugmbkEOIs6qWrZhg0LWeLziLrEwQJhs5mQ==";
      };
    };
    "assign-symbols-1.0.0" = {
      name = "assign-symbols";
      packageName = "assign-symbols";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assign-symbols/-/assign-symbols-1.0.0.tgz";
        sha512 = "Q+JC7Whu8HhmTdBph/Tq59IoRtoy6KAm5zzPv00WdujX82lbAL8K7WVjne7vdCsAmbF4AYaDOPyO3k0kl8qIrw==";
      };
    };
    "async-each-1.0.6" = {
      name = "async-each";
      packageName = "async-each";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-each/-/async-each-1.0.6.tgz";
        sha512 = "c646jH1avxr+aVpndVMeAfYw7wAa6idufrlN3LPA4PmKS0QEGp6PIC9nwz0WQkkvBGAMEki3pFdtxaF39J9vvg==";
      };
    };
    "atob-2.1.2" = {
      name = "atob";
      packageName = "atob";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/atob/-/atob-2.1.2.tgz";
        sha512 = "Wm6ukoaOGJi/73p/cl2GvLjTI5JM1k/O14isD73YML8StrH/7/lRFgmg8nICZgD3bZZvjwCGxtMOD3wWNAu8cg==";
      };
    };
    "base-0.11.2" = {
      name = "base";
      packageName = "base";
      version = "0.11.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/base/-/base-0.11.2.tgz";
        sha512 = "5T6P4xPgpp0YDFvSWwEZ4NoE3aM4QBQXDzmVbraCkFj8zHM+mba8SyqB5DbZWyR7mYHo6Y7BdQo3MoA4m0TeQg==";
      };
    };
    "basic-auth-2.0.1" = {
      name = "basic-auth";
      packageName = "basic-auth";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/basic-auth/-/basic-auth-2.0.1.tgz";
        sha512 = "NF+epuEdnUYVlGuhaxbbq+dvJttwLnGY+YixlXlME5KpQ5W3CnXA5cVTneY3SPbPDRkcjMbifrwmFYcClgOZeg==";
      };
    };
    "batch-0.6.1" = {
      name = "batch";
      packageName = "batch";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/batch/-/batch-0.6.1.tgz";
        sha512 = "x+VAiMRL6UPkx+kudNvxTl6hB2XNNCG2r+7wixVfIYwu/2HKRXimwQyaumLjMveWvT2Hkd/cAJw+QBMfJ/EKVw==";
      };
    };
    "bcryptjs-2.4.3" = {
      name = "bcryptjs";
      packageName = "bcryptjs";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcryptjs/-/bcryptjs-2.4.3.tgz";
        sha512 = "V/Hy/X9Vt7f3BbPJEi8BdVFMByHi+jNXrYkW3huaybV/kQ0KJg0Y6PkEMbn+zeT+i+SiKZ/HMqJGIIt4LZDqNQ==";
      };
    };
    "binary-extensions-1.13.1" = {
      name = "binary-extensions";
      packageName = "binary-extensions";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/binary-extensions/-/binary-extensions-1.13.1.tgz";
        sha512 = "Un7MIEDdUC5gNpcGDV97op1Ywk748MpHcFTHoYs6qnj1Z3j7I53VG3nwZhKzoBZmbdRNnb6WRdFlwl7tSDuZGw==";
      };
    };
    "bindings-1.5.0" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.5.0.tgz";
        sha512 = "p2q/t/mhvuOj/UeLlV6566GD/guowlr0hHxClI0W9m7MWYkL1F0hLo+0Aexs9HSPCtR1SXQ0TD3MMKrXZajbiQ==";
      };
    };
    "braces-2.3.2" = {
      name = "braces";
      packageName = "braces";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-2.3.2.tgz";
        sha512 = "aNdbnj9P8PjdXU4ybaWLK2IF3jc/EoDYbC7AazW6to3TRsfXxscC9UXOB5iDiEQrkyIbWp2SLQda4+QAa7nc3w==";
      };
    };
    "cache-base-1.0.1" = {
      name = "cache-base";
      packageName = "cache-base";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cache-base/-/cache-base-1.0.1.tgz";
        sha512 = "AKcdTnFSWATd5/GCPRxr2ChwIJ85CeyrEyjRHlKxQ56d4XJMGym0uAiKn0xbLOGOl3+yRpOTi484dVCEc5AUzQ==";
      };
    };
    "chokidar-2.1.8" = {
      name = "chokidar";
      packageName = "chokidar";
      version = "2.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/chokidar/-/chokidar-2.1.8.tgz";
        sha512 = "ZmZUazfOzf0Nve7duiCKD23PFSCs4JPoYyccjUFF3aQkQadqBhfzhjkwBH2mNOG9cTBwhamM37EIsIkZw3nRgg==";
      };
    };
    "class-utils-0.3.6" = {
      name = "class-utils";
      packageName = "class-utils";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/class-utils/-/class-utils-0.3.6.tgz";
        sha512 = "qOhPa/Fj7s6TY8H8esGu5QNpMMQxz79h+urzrNYN6mn+9BnxlDGf5QZ+XeCDsxSjPqsSR56XOZOJmpeurnLMeg==";
      };
    };
    "collection-visit-1.0.0" = {
      name = "collection-visit";
      packageName = "collection-visit";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/collection-visit/-/collection-visit-1.0.0.tgz";
        sha512 = "lNkKvzEeMBBjUGHZ+q6z9pSJla0KWAQPvtzhEV9+iGyQYG+pBpl7xKDhxoNSOZH2hhv0v5k0y2yAM4o4SjoSkw==";
      };
    };
    "colors-1.4.0" = {
      name = "colors";
      packageName = "colors";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.4.0.tgz";
        sha512 = "a+UqTh4kgZg/SlGvfbzDHpgRu7AAQOmmqRHJnxhRZICKFUT91brVhNNt58CMWU9PsBbv3PDCZUHbVxuDiH2mtA==";
      };
    };
    "component-emitter-1.3.1" = {
      name = "component-emitter";
      packageName = "component-emitter";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/component-emitter/-/component-emitter-1.3.1.tgz";
        sha512 = "T0+barUSQRTUQASh8bx02dl+DhF54GtIDY13Y3m9oWTklKbb3Wv974meRpeZ3lp1JpLVECWWNHC4vaG2XHXouQ==";
      };
    };
    "connect-3.7.0" = {
      name = "connect";
      packageName = "connect";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/connect/-/connect-3.7.0.tgz";
        sha512 = "ZqRXc+tZukToSNmh5C2iWMSoV3X1YUcPbqEM4DkEG5tNQXrQUZCNVGGv3IuicnkMtPfGf3Xtp8WCXs295iQ1pQ==";
      };
    };
    "copy-descriptor-0.1.1" = {
      name = "copy-descriptor";
      packageName = "copy-descriptor";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/copy-descriptor/-/copy-descriptor-0.1.1.tgz";
        sha512 = "XgZ0pFcakEUlbwQEVNg3+QAis1FyTL3Qel9FYy8pSkQqoG3PNoT0bOCQtOXcOkur21r2Eq2kI+IE+gsmAEVlYw==";
      };
    };
    "core-util-is-1.0.3" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.3.tgz";
        sha512 = "ZQBvi1DcpJ4GDqanjucZ2Hj3wEO5pZDS89BWbkcrvdxksJorwUDDZamX9ldFkp9aw2lmBDLgkObEA4DWNJ9FYQ==";
      };
    };
    "cors-2.8.5" = {
      name = "cors";
      packageName = "cors";
      version = "2.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cors/-/cors-2.8.5.tgz";
        sha512 = "KIHbLJqu73RGr/hnbrO9uBeixNGuvSQjul/jdFvS/KFSIH1hWVd1ng7zOHx+YrEfInLG7q4n6GHQ9cDtxv/P6g==";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "decode-uri-component-0.2.2" = {
      name = "decode-uri-component";
      packageName = "decode-uri-component";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-uri-component/-/decode-uri-component-0.2.2.tgz";
        sha512 = "FqUYQ+8o158GyGTrMFJms9qh3CqTKvAqgqsTnkLI8sKu0028orqBhxNMFkFen0zGyg6epACD32pjVk58ngIErQ==";
      };
    };
    "define-property-0.2.5" = {
      name = "define-property";
      packageName = "define-property";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-0.2.5.tgz";
        sha512 = "Rr7ADjQZenceVOAKop6ALkkRAmH1A4Gx9hV/7ZujPUN2rkATqFO0JZLZInbAjpZYoJ1gUx8MRMQVkYemcbMSTA==";
      };
    };
    "define-property-1.0.0" = {
      name = "define-property";
      packageName = "define-property";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-1.0.0.tgz";
        sha512 = "cZTYKFWspt9jZsMscWo8sc/5lbPC9Q0N5nBLgb+Yd915iL3udB1uFgS3B8YCx66UVHq018DAVFoee7x+gxggeA==";
      };
    };
    "define-property-2.0.2" = {
      name = "define-property";
      packageName = "define-property";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-property/-/define-property-2.0.2.tgz";
        sha512 = "jwK2UV4cnPpbcG7+VRARKTZPUWowwXA8bzH5NP6ud0oeAxyYPuGZUAC7hMugpCdz4BeSZl2Dl9k66CHJ/46ZYQ==";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha512 = "7emPTl6Dpo6JRXOXjLRxck+FlLRX5847cLKEn00PLAgc3g2hTZZgr+e4c2v6QpSmLeFP3n5yUo7ft6avBK/5jQ==";
      };
    };
    "depd-2.0.0" = {
      name = "depd";
      packageName = "depd";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-2.0.0.tgz";
        sha512 = "g7nH6P6dyDioJogAAGprGpCtVImJhpPk/roCzdb3fIh61/s/nPsfR6onyMwkCAR/OlC3yBC0lESvUoQEAssIrw==";
      };
    };
    "destroy-1.2.0" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.2.0.tgz";
        sha512 = "2sJGJTaXIIaR1w4iJSNoN0hnMY7Gpc/n8D4qSCJw8QqFWXf7cuAgnEHxBpweaVcPevC2l3KpjYCx3NypQQgaJg==";
      };
    };
    "duplexer-0.1.2" = {
      name = "duplexer";
      packageName = "duplexer";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexer/-/duplexer-0.1.2.tgz";
        sha512 = "jtD6YG370ZCIi/9GTaJKQxWTZD045+4R4hTk/x1UyoqadyJ9x9CgSi1RlVDQF8U2sxLLSnFkCaMihqljHIWgMg==";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha512 = "WMwm9LhRUo+WUaRN+vRuETqG89IgZphVSNkdFgeb6sS/E4OrDIN7t48CAewSHXc6C8lefD8KKfr5vY61brQlow==";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha512 = "TPJXq8JqFaVYm2CWmPvnP2Iyo4ZSM7/QKcSmuMLDObfpH5fi7RUGmd/rTDf+rut/saiDiQEeVTNgAmJEdAOx0w==";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha512 = "NiSupZ4OeuGwr68lGIeym/ksIZMJodUGOSCZ/FSnTxcrekbvqrgdUxlJOMpijaKZVjAJrWrGs/6Jy8OMuyj9ow==";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha512 = "aIL5Fx7mawVa300al2BnEE4iNvo1qETxLrPI/o05L7z6go7fCw1J6EQmbK4FmJ2AS7kgVF/KEZWufBfdClMcPg==";
      };
    };
    "event-stream-3.3.4" = {
      name = "event-stream";
      packageName = "event-stream";
      version = "3.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-stream/-/event-stream-3.3.4.tgz";
        sha512 = "QHpkERcGsR0T7Qm3HNJSyXKEEj8AHNxkY3PK8TS2KJvQ7NiSHe3DDpwVKKtoYprL/AreyzFBeIkBIWChAqn60g==";
      };
    };
    "expand-brackets-2.1.4" = {
      name = "expand-brackets";
      packageName = "expand-brackets";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/expand-brackets/-/expand-brackets-2.1.4.tgz";
        sha512 = "w/ozOKR9Obk3qoWeY/WDi6MFta9AoMR+zud60mdnbniMcBxRuFJyDt2LdX/14A1UABeqk+Uk+LDfUpvoGKppZA==";
      };
    };
    "extend-shallow-2.0.1" = {
      name = "extend-shallow";
      packageName = "extend-shallow";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend-shallow/-/extend-shallow-2.0.1.tgz";
        sha512 = "zCnTtlxNoAiDc3gqY2aYAWFx7XWWiasuF2K8Me5WbN8otHKTUKBwjPtNpRs/rbUZm7KxWAaNj7P1a/p52GbVug==";
      };
    };
    "extend-shallow-3.0.2" = {
      name = "extend-shallow";
      packageName = "extend-shallow";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend-shallow/-/extend-shallow-3.0.2.tgz";
        sha512 = "BwY5b5Ql4+qZoefgMj2NUmx+tehVTH/Kf4k1ZEtOHNFcm2wSxMRo992l6X3TIgni2eZVTZ85xMOjF31fwZAj6Q==";
      };
    };
    "extglob-2.0.4" = {
      name = "extglob";
      packageName = "extglob";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/extglob/-/extglob-2.0.4.tgz";
        sha512 = "Nmb6QXkELsuBr24CJSkilo6UHHgbekK5UiZgfE6UHD3Eb27YC6oD+bhcT+tJ6cl8dmsgdQxnWlcry8ksBIBLpw==";
      };
    };
    "faye-websocket-0.11.4" = {
      name = "faye-websocket";
      packageName = "faye-websocket";
      version = "0.11.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/faye-websocket/-/faye-websocket-0.11.4.tgz";
        sha512 = "CzbClwlXAuiRQAlUyfqPgvPoNKTckTPGfwZV4ZdAhVcP2lh9KUxJg2b5GkE7XbjKQ3YJnQ9z6D9ntLAlB+tP8g==";
      };
    };
    "file-uri-to-path-1.0.0" = {
      name = "file-uri-to-path";
      packageName = "file-uri-to-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/file-uri-to-path/-/file-uri-to-path-1.0.0.tgz";
        sha512 = "0Zt+s3L7Vf1biwWZ29aARiVYLx7iMGnEUl9x33fbB/j3jR81u/O2LbqK+Bm1CDSNDKVtJ/YjwY7TUd5SkeLQLw==";
      };
    };
    "fill-range-4.0.0" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-4.0.0.tgz";
        sha512 = "VcpLTWqWDiTerugjj8e3+esbg+skS3M9e54UuR3iCeIDMXCLTsAH8hTSzDQU/X6/6t3eYkOKoZSef2PlU6U1XQ==";
      };
    };
    "finalhandler-1.1.2" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.1.2.tgz";
        sha512 = "aAWcW57uxVNrQZqFXjITpW3sIUQmHGG3qSb9mUah9MgMC4NeWhNOlNjXEYq3HjRAvL6arUviZGGJsBg6z0zsWA==";
      };
    };
    "for-in-1.0.2" = {
      name = "for-in";
      packageName = "for-in";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/for-in/-/for-in-1.0.2.tgz";
        sha512 = "7EwmXrOjyL+ChxMhmG5lnW9MPt1aIeZEwKhQzoBUdTV0N3zuwWDZYVJatDvZ2OyzPUvdIAZDsCetk3coyMfcnQ==";
      };
    };
    "fragment-cache-0.2.1" = {
      name = "fragment-cache";
      packageName = "fragment-cache";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fragment-cache/-/fragment-cache-0.2.1.tgz";
        sha512 = "GMBAbW9antB8iZRHLoGw0b3HANt57diZYFO/HL1JGIC1MjKrdmhxvrJbupnVvpys0zsz7yBApXdQyfepKly2kA==";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha512 = "zJ2mQYM18rEFOudeV4GShTGIQ7RbzA7ozbU9I/XBpm7kqgMywgmylMwXHxZJmkVoYkna9d2pVXVXPdYTP9ej8Q==";
      };
    };
    "from-0.1.7" = {
      name = "from";
      packageName = "from";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/from/-/from-0.1.7.tgz";
        sha512 = "twe20eF1OxVxp/ML/kq2p1uc6KvFK/+vs8WjEbeKmV2He22MKm7YF2ANIt+EOqhJ5L3K/SuuPhk0hWQDjOM23g==";
      };
    };
    "fsevents-1.2.13" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "1.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-1.2.13.tgz";
        sha512 = "oWb1Z6mkHIskLzEJ/XWX0srkpkTQ7vaopMQkyaEIoq0fmtFVxOthb8cCxeT+p3ynTdkk/RZwbgG4brR5BeWECw==";
      };
    };
    "function-bind-1.1.2" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.2.tgz";
        sha512 = "7XHNxH7qX9xG5mIwxkhumTox/MIRNcOgDrxWsMt2pAr23WHp6MrRlN7FBSFpCpr+oVO0F744iUgR82nJMfG2SA==";
      };
    };
    "get-value-2.0.6" = {
      name = "get-value";
      packageName = "get-value";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/get-value/-/get-value-2.0.6.tgz";
        sha512 = "Ln0UQDlxH1BapMu3GPtf7CuYNwRZf2gwCuPqbyG6pB8WfmFpzqcy4xtAaAMUhnNqjMKTiCPZG2oMT3YSx8U2NA==";
      };
    };
    "glob-parent-3.1.0" = {
      name = "glob-parent";
      packageName = "glob-parent";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob-parent/-/glob-parent-3.1.0.tgz";
        sha512 = "E8Ak/2+dZY6fnzlR7+ueWvhsH1SjHr4jjss4YS/h4py44jY9MhK/VFdaZJAWDz6BbL21KeteKxFSFpq8OS5gVA==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "has-value-0.3.1" = {
      name = "has-value";
      packageName = "has-value";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-value/-/has-value-0.3.1.tgz";
        sha512 = "gpG936j8/MzaeID5Yif+577c17TxaDmhuyVgSwtnL/q8UUTySg8Mecb+8Cf1otgLoD7DDH75axp86ER7LFsf3Q==";
      };
    };
    "has-value-1.0.0" = {
      name = "has-value";
      packageName = "has-value";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-value/-/has-value-1.0.0.tgz";
        sha512 = "IBXk4GTsLYdQ7Rvt+GRBrFSVEkmuOUy4re0Xjd9kJSUQpnTrWR4/y9RpfexN9vkAPMFuQoeWKwqzPozRTlasGw==";
      };
    };
    "has-values-0.1.4" = {
      name = "has-values";
      packageName = "has-values";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-values/-/has-values-0.1.4.tgz";
        sha512 = "J8S0cEdWuQbqD9//tlZxiMuMNmxB8PlEwvYwuxsTmR1G5RXUePEX/SJn7aD0GMLieuZYSwNH0cQuJGwnYunXRQ==";
      };
    };
    "has-values-1.0.0" = {
      name = "has-values";
      packageName = "has-values";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-values/-/has-values-1.0.0.tgz";
        sha512 = "ODYZC64uqzmtfGMEAX/FvZiRyWLpAC3vYnNunURUnkGVTS+mI0smVsWaPydRBsE3g+ok7h960jChO8mFcWlHaQ==";
      };
    };
    "hasown-2.0.2" = {
      name = "hasown";
      packageName = "hasown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/hasown/-/hasown-2.0.2.tgz";
        sha512 = "0hJU9SCPvmMzIBdZFqNPXWa6dqh7WdH0cII9y+CyS8rG3nL48Bclra9HmKhVVUHyPWNH5Y7xDwAB7bfgSjkUMQ==";
      };
    };
    "http-auth-3.1.3" = {
      name = "http-auth";
      packageName = "http-auth";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-auth/-/http-auth-3.1.3.tgz";
        sha512 = "Jbx0+ejo2IOx+cRUYAGS1z6RGc6JfYUNkysZM4u4Sfk1uLlGv814F7/PIjQQAuThLdAWxb74JMGd5J8zex1VQg==";
      };
    };
    "http-errors-1.6.3" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.6.3.tgz";
        sha512 = "lks+lVC8dgGyh97jxvxeYTWQFvh4uw4yC12gVl63Cg30sjPX4wuGcdkICVXDAESr6OJGjqGA8Iz5mkeN6zlD7A==";
      };
    };
    "http-errors-2.0.0" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-2.0.0.tgz";
        sha512 = "FtwrG/euBzaEjYeRqOgly7G0qviiXoJWnvEH2Z1plBdXgbyjv34pHTSb9zoeHMyDy33+DWy5Wt9Wo+TURtOYSQ==";
      };
    };
    "http-parser-js-0.5.8" = {
      name = "http-parser-js";
      packageName = "http-parser-js";
      version = "0.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-parser-js/-/http-parser-js-0.5.8.tgz";
        sha512 = "SGeBX54F94Wgu5RH3X5jsDtf4eHyRogWX1XGT3b4HuW3tQPM4AaBzoUji/4AAJNXCEOWZ5O0DgZmJw1947gD5Q==";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha512 = "x00IRNXNy63jwGkJmzPigoySHbaqpNuzKbBOmzK+g2OdZpQ9w+sxCN+VSB3ja7IAge2OP2qpfxTjeNcyjmW1uw==";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-accessor-descriptor-1.0.1" = {
      name = "is-accessor-descriptor";
      packageName = "is-accessor-descriptor";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-accessor-descriptor/-/is-accessor-descriptor-1.0.1.tgz";
        sha512 = "YBUanLI8Yoihw923YeFUS5fs0fF2f5TSFTNiYAAzhhDscDa3lEqYuz1pDOEP5KvX94I9ey3vsqjJcLVFVU+3QA==";
      };
    };
    "is-binary-path-1.0.1" = {
      name = "is-binary-path";
      packageName = "is-binary-path";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-binary-path/-/is-binary-path-1.0.1.tgz";
        sha512 = "9fRVlXc0uCxEDj1nQzaWONSpbTfx0FmJfzHF7pwlI8DkWGoHBBea4Pg5Ky0ojwwxQmnSifgbKkI06Qv0Ljgj+Q==";
      };
    };
    "is-buffer-1.1.6" = {
      name = "is-buffer";
      packageName = "is-buffer";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-buffer/-/is-buffer-1.1.6.tgz";
        sha512 = "NcdALwpXkTm5Zvvbk7owOUSvVvBKDgKP5/ewfXEznmQFfs4ZRmanOeKBTjRVjka3QFoN6XJ+9F3USqfHqTaU5w==";
      };
    };
    "is-data-descriptor-1.0.1" = {
      name = "is-data-descriptor";
      packageName = "is-data-descriptor";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-data-descriptor/-/is-data-descriptor-1.0.1.tgz";
        sha512 = "bc4NlCDiCr28U4aEsQ3Qs2491gVq4V8G7MQyws968ImqjKuYtTJXrl7Vq7jsN7Ly/C3xj5KWFrY7sHNeDkAzXw==";
      };
    };
    "is-descriptor-0.1.7" = {
      name = "is-descriptor";
      packageName = "is-descriptor";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-descriptor/-/is-descriptor-0.1.7.tgz";
        sha512 = "C3grZTvObeN1xud4cRWl366OMXZTj0+HGyk4hvfpx4ZHt1Pb60ANSXqCK7pdOTeUQpRzECBSTphqvD7U+l22Eg==";
      };
    };
    "is-descriptor-1.0.3" = {
      name = "is-descriptor";
      packageName = "is-descriptor";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-descriptor/-/is-descriptor-1.0.3.tgz";
        sha512 = "JCNNGbwWZEVaSPtS45mdtrneRWJFp07LLmykxeFV5F6oBvNF8vHSfJuJgoT472pSfk+Mf8VnlrspaFBHWM8JAw==";
      };
    };
    "is-extendable-0.1.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-0.1.1.tgz";
        sha512 = "5BMULNob1vgFX6EjQw5izWDxrecWK9AM72rugNr0TFldMOi0fj6Jk+zeKIt0xGj4cEfQIJth4w3OKWOJ4f+AFw==";
      };
    };
    "is-extendable-1.0.1" = {
      name = "is-extendable";
      packageName = "is-extendable";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extendable/-/is-extendable-1.0.1.tgz";
        sha512 = "arnXMxT1hhoKo9k1LZdmlNyJdDDfy2v0fXjFlmok4+i8ul/6WlbVge9bhM74OpNPQPMGUToDtz+KXa1PneJxOA==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-3.1.0" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-3.1.0.tgz";
        sha512 = "UFpDDrPgM6qpnFNI+rh/p3bUaq9hKLZN8bMUWzxmcnZVS3omf4IPK+BrewlnWjO1WmUsMYuSjKh4UJuV4+Lqmw==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-3.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-3.0.0.tgz";
        sha512 = "4cboCqIpliH+mAvFNegjZQ4kgKc3ZUhQVr3HvWbSh5q3WH2v82ct+T2Y1hdU5Gdtorx/cLifQjqCbL7bpznLTg==";
      };
    };
    "is-plain-object-2.0.4" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-2.0.4.tgz";
        sha512 = "h5PpgXkWitc38BBMYawTYMWJHFZJVnBquFE57xFpjB8pJFiF6gZ+bU+WyI/yqXiFR5mdLsgYNaPe8uao6Uv9Og==";
      };
    };
    "is-windows-1.0.2" = {
      name = "is-windows";
      packageName = "is-windows";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-windows/-/is-windows-1.0.2.tgz";
        sha512 = "eXK1UInq2bPmjyX6e3VHIzMLobc4J94i4AWn+Hpq3OU5KkrRC96OAcR3PRJ/pGu6m8TRnBHP9dkXQVsT/COVIA==";
      };
    };
    "is-wsl-1.1.0" = {
      name = "is-wsl";
      packageName = "is-wsl";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-wsl/-/is-wsl-1.1.0.tgz";
        sha512 = "gfygJYZ2gLTDlmbWMI0CE2MwnFzSN/2SZfkMlItC4K/JBlsWVDB0bO6XhqcY13YXE7iMcAJnzTCJjPiTeJJ0Mw==";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha512 = "VLghIWNM6ELQzo7zwmcg0NmTVyWKYjvIeM83yjp0wRDTmUnrM678fQbcKBo6n2CJEF0szoG//ytg+TKla89ALQ==";
      };
    };
    "isobject-2.1.0" = {
      name = "isobject";
      packageName = "isobject";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-2.1.0.tgz";
        sha512 = "+OUdGJlgjOBZDfxnDjYYG6zp487z0JGNQq3cYQYg5f5hKR+syHMsaztzGeml/4kGG55CSpKSpWTY+jYGgsHLgA==";
      };
    };
    "isobject-3.0.1" = {
      name = "isobject";
      packageName = "isobject";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isobject/-/isobject-3.0.1.tgz";
        sha512 = "WhB9zCku7EGTj/HQQRz5aUQEUeoQZH2bWcltRErOpymJ4boYE6wL9Tbr23krRPSZ+C5zqNSrSw+Cc7sZZ4b7vg==";
      };
    };
    "kind-of-3.2.2" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-3.2.2.tgz";
        sha512 = "NOW9QQXMoZGg/oqnVNoNTTIFEIid1627WCffUBJEdMxYApq7mNE7CpzucIPc+ZQg25Phej7IJSmX3hO+oblOtQ==";
      };
    };
    "kind-of-4.0.0" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-4.0.0.tgz";
        sha512 = "24XsCxmEbRwEDbz/qz3stgin8TTzZ1ESR56OMCN0ujYg+vRutNSiOj9bHH9u85DKgXguraugV5sFuvbD4FW/hw==";
      };
    };
    "kind-of-6.0.3" = {
      name = "kind-of";
      packageName = "kind-of";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.3.tgz";
        sha512 = "dcS1ul+9tmeD95T+x28/ehLgd9mENa3LsvDTtzm3vyBEO7RPptvAD+t44WVXaUjTBRcrpFeFlC8WCruUR456hw==";
      };
    };
    "map-cache-0.2.2" = {
      name = "map-cache";
      packageName = "map-cache";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-cache/-/map-cache-0.2.2.tgz";
        sha512 = "8y/eV9QQZCiyn1SprXSrCmqJN0yNRATe+PO8ztwqrvrbdRLA3eYJF0yaR0YayLWkMbsQSKWS9N2gPcGEc4UsZg==";
      };
    };
    "map-stream-0.1.0" = {
      name = "map-stream";
      packageName = "map-stream";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-stream/-/map-stream-0.1.0.tgz";
        sha512 = "CkYQrPYZfWnu/DAmVCpTSX/xHpKZ80eKh2lAkyA6AJTef6bW+6JpbQZN5rofum7da+SyN1bi5ctTm+lTfcCW3g==";
      };
    };
    "map-visit-1.0.0" = {
      name = "map-visit";
      packageName = "map-visit";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/map-visit/-/map-visit-1.0.0.tgz";
        sha512 = "4y7uGv8bd2WdM9vpQsiQNo41Ln1NvhvDRuVt0k2JZQ+ezN2uaQes7lZeZ+QQUHOLQAtDaBJ+7wCbi+ab/KFs+w==";
      };
    };
    "micromatch-3.1.10" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "3.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-3.1.10.tgz";
        sha512 = "MWikgl9n9M3w+bpsY3He8L+w9eF9338xRl8IAO5viDizwSzziFEyUzo2xrrloB64ADbTf8uA8vRqqttDTOmccg==";
      };
    };
    "mime-1.6.0" = {
      name = "mime";
      packageName = "mime";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.6.0.tgz";
        sha512 = "x0Vn8spI+wuJ1O6S7gnbaQg8Pxh4NNHb7KSINmEWKiPE4RKOplvijn+NkmYmmRgP68mc70j2EbeTFRsrswaQeg==";
      };
    };
    "mime-db-1.52.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.52.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.52.0.tgz";
        sha512 = "sPU4uV7dYlvtWJxwwxHD0PuihVNiE7TyAbQ5SWxDCB9mUYvOgroQOwYQQOKPJ8CIbE+1ETVlOoK1UC2nU3gYvg==";
      };
    };
    "mime-types-2.1.35" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.35";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.35.tgz";
        sha512 = "ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==";
      };
    };
    "mixin-deep-1.3.2" = {
      name = "mixin-deep";
      packageName = "mixin-deep";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mixin-deep/-/mixin-deep-1.3.2.tgz";
        sha512 = "WRoDn//mXBiJ1H40rqa3vH0toePwSsGb45iInWlTySa+Uu4k3tYUSxa2v1KqAiLtvlrSzaExqS1gtk96A9zvEA==";
      };
    };
    "morgan-1.10.0" = {
      name = "morgan";
      packageName = "morgan";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/morgan/-/morgan-1.10.0.tgz";
        sha512 = "AbegBVI4sh6El+1gNwvD5YIck7nSA36weD7xvIxG4in80j/UoK8AEGaWnnz8v1GxonMCltmlNs5ZKbGvl9b1XQ==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha512 = "Tpp60P6IUJDTuOq/5Z8cdskzJujfwqfOTkrwIwj7IRISpnkJnT6SyJ4PCPnGMoFjC9ddhal5KVIYtAt97ix05A==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "nan-2.20.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.20.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.20.0.tgz";
        sha512 = "bk3gXBZDGILuuo/6sKtr0DQmSThYHLtNCdSdXk9YkxD/jK6X2vmCyyXBBxyqZ4XcnzTyYEAThfX3DCEnLf6igw==";
      };
    };
    "nanomatch-1.2.13" = {
      name = "nanomatch";
      packageName = "nanomatch";
      version = "1.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanomatch/-/nanomatch-1.2.13.tgz";
        sha512 = "fpoe2T0RbHwBTBUOftAfBPaDEi06ufaUai0mE6Yn1kacc3SnTErfb/h+X94VXzI64rKFHYImXSvdwGGCmwOqCA==";
      };
    };
    "negotiator-0.6.3" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.3.tgz";
        sha512 = "+EUsqGPLsM+j/zdChZjsnX51g4XrHFOIXwfnCVPGlQk/k5giakcKsuxCObBRu6DSm9opw/O6slWbJdghQM4bBg==";
      };
    };
    "normalize-path-2.1.1" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-2.1.1.tgz";
        sha512 = "3pKJwH184Xo/lnH6oyP1q2pMd7HcypqqmRs91/6/i2CGtWwIKGCkOOMTm/zXbgTEWHw1uNpNi/igc3ePOYHb6w==";
      };
    };
    "normalize-path-3.0.0" = {
      name = "normalize-path";
      packageName = "normalize-path";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-path/-/normalize-path-3.0.0.tgz";
        sha512 = "6eZs5Ls3WtCisHWp9S2GUy8dqkpGi4BVSz3GaqiE6ezub0512ESztXUwUB6C6IKbQkY2Pnb/mD4WYojCRwcwLA==";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha512 = "rJgTQnkUnH1sFw8yT6VSU3zD3sWmu6sZhIseY8VX+GRu3P6F7Fu+JNDoXfklElbLJSnc3FUQHVe4cU5hj+BcUg==";
      };
    };
    "object-copy-0.1.0" = {
      name = "object-copy";
      packageName = "object-copy";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-copy/-/object-copy-0.1.0.tgz";
        sha512 = "79LYn6VAb63zgtmAteVOWo9Vdj71ZVBy3Pbse+VqxDpEP83XuujMrGqHIwAXJ5I/aM0zU7dIyIAhifVTPrNItQ==";
      };
    };
    "object-visit-1.0.1" = {
      name = "object-visit";
      packageName = "object-visit";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-visit/-/object-visit-1.0.1.tgz";
        sha512 = "GBaMwwAVK9qbQN3Scdo0OyvgPW7l3lnaVMj84uTOZlswkX0KpF6fyDBJhtTthf7pymztoN36/KEr1DyhF96zEA==";
      };
    };
    "object.pick-1.3.0" = {
      name = "object.pick";
      packageName = "object.pick";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.pick/-/object.pick-1.3.0.tgz";
        sha512 = "tqa/UMy/CCoYmj+H5qc07qvSL9dqcs/WZENZ1JbtWBlATP+iVOe778gE6MSijnyCnORzDuX6hU+LA4SZ09YjFQ==";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha512 = "ikqdkGAAyf/X/gPhXGvfgAytDZtDbr+bkNUJ0N9h5MI/dmdgCs3l6hoHrcUv41sRKew3jIwrp4qQDXiK99Utww==";
      };
    };
    "on-finished-2.4.1" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.4.1.tgz";
        sha512 = "oVlzkg3ENAhCk2zdv7IJwd/QUD4z2RxRwpkcGY8psCVcCYZNq4wYnVWALHM+brtuJjePWiYF/ClmuDr8Ch5+kg==";
      };
    };
    "on-headers-1.0.2" = {
      name = "on-headers";
      packageName = "on-headers";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-headers/-/on-headers-1.0.2.tgz";
        sha512 = "pZAE+FJLoyITytdqK0U5s+FIpjN0JP3OzFi/u8Rx+EV5/W+JTWGXG8xFzevE7AjBfDqHv/8vL8qQsIhHnqRkrA==";
      };
    };
    "opn-6.0.0" = {
      name = "opn";
      packageName = "opn";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/opn/-/opn-6.0.0.tgz";
        sha512 = "I9PKfIZC+e4RXZ/qr1RhgyCnGgYX0UEIlXgWnCOVACIvFgaC9rz6Won7xbdhoHrd8IIhV7YEpHjreNUNkqCGkQ==";
      };
    };
    "parseurl-1.3.3" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.3.tgz";
        sha512 = "CiyeOxFT/JZyN5m0z9PfXw4SCBJ6Sygz1Dpl0wqjlhDEGGBP1GnsUVEL0p63hoG1fcj3fHynXi9NYO4nWOL+qQ==";
      };
    };
    "pascalcase-0.1.1" = {
      name = "pascalcase";
      packageName = "pascalcase";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pascalcase/-/pascalcase-0.1.1.tgz";
        sha512 = "XHXfu/yOQRy9vYOtUDVMN60OEJjW013GoObG1o+xwQTpB9eYJX/BjXMsdW13ZDPruFhYYn0AG22w0xgQMwl3Nw==";
      };
    };
    "path-dirname-1.0.2" = {
      name = "path-dirname";
      packageName = "path-dirname";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-dirname/-/path-dirname-1.0.2.tgz";
        sha512 = "ALzNPpyNq9AqXMBjeymIjFDAkAFH06mHJH/cSBHAgU0s4vfpBn6b2nf8tiRLvagKD8RbTpq2FKTBg7cl9l3c7Q==";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha512 = "AVbw3UJ2e9bq64vSaS9Am0fje1Pa8pbGqTTsmXfaIiMpnr5DlDhfJOuLj9Sf95ZPVDAUerDfEk88MPmPe7UCQg==";
      };
    };
    "pause-stream-0.0.11" = {
      name = "pause-stream";
      packageName = "pause-stream";
      version = "0.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/pause-stream/-/pause-stream-0.0.11.tgz";
        sha512 = "e3FBlXLmN/D1S+zHzanP4E/4Z60oFAa3O051qt1pxa7DEJWKAyil6upYVXCWadEnuoqa4Pkc9oUx9zsxYeRv8A==";
      };
    };
    "posix-character-classes-0.1.1" = {
      name = "posix-character-classes";
      packageName = "posix-character-classes";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/posix-character-classes/-/posix-character-classes-0.1.1.tgz";
        sha512 = "xTgYBc3fuo7Yt7JbiuFxSYGToMoz8fLoE6TC9Wx1P/u+LfeThMOAqmuyECnlBaaJb+u1m9hHiXUEtwW4OzfUJg==";
      };
    };
    "process-nextick-args-2.0.1" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-2.0.1.tgz";
        sha512 = "3ouUOpQhtgrbOa17J7+uxOTpITYWaGP7/AhoR3+A+/1e9skrzelGi/dXzEYyvbxubEF6Wn2ypscTKiKJFFn1ag==";
      };
    };
    "proxy-middleware-0.15.0" = {
      name = "proxy-middleware";
      packageName = "proxy-middleware";
      version = "0.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-middleware/-/proxy-middleware-0.15.0.tgz";
        sha512 = "EGCG8SeoIRVMhsqHQUdDigB2i7qU7fCsWASwn54+nPutYO8n4q6EiwMzyfWlC+dzRFExP+kvcnDFdBDHoZBU7Q==";
      };
    };
    "range-parser-1.2.1" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.1.tgz";
        sha512 = "Hrgsx+orqoygnmhFbKaHE6c296J+HTAQXoxEF6gNupROmmGJRoyzfG3ccAveqCBrwr/2yxQ5BVd/GTl5agOwSg==";
      };
    };
    "readable-stream-2.3.8" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.3.8.tgz";
        sha512 = "8p0AUk4XODgIewSi0l8Epjs+EVnWiK7NoDIEGU0HhE7+ZyY8D1IMY7odu5lRrFXGg71L15KG8QrPmum45RTtdA==";
      };
    };
    "readdirp-2.2.1" = {
      name = "readdirp";
      packageName = "readdirp";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdirp/-/readdirp-2.2.1.tgz";
        sha512 = "1JU/8q+VgFZyxwrJ+SVIOsh+KywWGpds3NTqikiKpDMZWScmAYyKIgqkO+ARvNWJfXeXR1zxz7aHF4u4CyH6vQ==";
      };
    };
    "regex-not-1.0.2" = {
      name = "regex-not";
      packageName = "regex-not";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/regex-not/-/regex-not-1.0.2.tgz";
        sha512 = "J6SDjUgDxQj5NusnOtdFxDwN/+HWykR8GELwctJ7mdqhcyy1xEc4SRFHUXvxTp661YaVKAjfRLZ9cCqS6tn32A==";
      };
    };
    "remove-trailing-separator-1.1.0" = {
      name = "remove-trailing-separator";
      packageName = "remove-trailing-separator";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remove-trailing-separator/-/remove-trailing-separator-1.1.0.tgz";
        sha512 = "/hS+Y0u3aOfIETiaiirUFwDBDzmXPvO+jAfKTitUngIPzdKc6Z0LoFjM/CK5PL4C+eKwHohlHAb6H0VFfmmUsw==";
      };
    };
    "repeat-element-1.1.4" = {
      name = "repeat-element";
      packageName = "repeat-element";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-element/-/repeat-element-1.1.4.tgz";
        sha512 = "LFiNfRcSu7KK3evMyYOuCzv3L10TW7yC1G2/+StMjK8Y6Vqd2MG7r/Qjw4ghtuCOjFvlnms/iMmLqpvW/ES/WQ==";
      };
    };
    "repeat-string-1.6.1" = {
      name = "repeat-string";
      packageName = "repeat-string";
      version = "1.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/repeat-string/-/repeat-string-1.6.1.tgz";
        sha512 = "PV0dzCYDNfRi1jCDbJzpW7jNNDRuCOG/jI5ctQcGKt/clZD+YcPS3yIlWuTJMmESC8aevCFmWJy5wjAFgNqN6w==";
      };
    };
    "resolve-url-0.2.1" = {
      name = "resolve-url";
      packageName = "resolve-url";
      version = "0.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-url/-/resolve-url-0.2.1.tgz";
        sha512 = "ZuF55hVUQaaczgOIwqWzkEcEidmlD/xl44x1UZnhOXcYuFN2S6+rcxpG+C1N3So0wvNI3DmJICUFfu2SxhBmvg==";
      };
    };
    "ret-0.1.15" = {
      name = "ret";
      packageName = "ret";
      version = "0.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/ret/-/ret-0.1.15.tgz";
        sha512 = "TTlYpa+OL+vMMNG24xSlQGEJ3B/RzEfUlLct7b5G/ytav+wPrplCpVMFuwzXbkecJrb6IYo1iFb0S9v37754mg==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-regex-1.1.0" = {
      name = "safe-regex";
      packageName = "safe-regex";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-regex/-/safe-regex-1.1.0.tgz";
        sha512 = "aJXcif4xnaNUzvUuC5gcb46oTS7zvg4jpMTnuqtrEPlR3vFr4pxtdTwaF1Qs3Enjn9HK+ZlwQui+a7z0SywIzg==";
      };
    };
    "send-0.18.0" = {
      name = "send";
      packageName = "send";
      version = "0.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.18.0.tgz";
        sha512 = "qqWzuOjSFOuqPjFe4NOsMLafToQQwBSOEpS+FwEt3A2V3vKubTquT3vmLTQpFgMXp8AlFWFuP1qKaJZOtPpVXg==";
      };
    };
    "serve-index-1.9.1" = {
      name = "serve-index";
      packageName = "serve-index";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-index/-/serve-index-1.9.1.tgz";
        sha512 = "pXHfKNP4qujrtteMrSBb0rc8HJ9Ms/GrXwcUtUtD5s4ewDJI8bT3Cz2zTVRMKtri49pLx2e0Ya8ziP5Ya2pZZw==";
      };
    };
    "set-value-2.0.1" = {
      name = "set-value";
      packageName = "set-value";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-value/-/set-value-2.0.1.tgz";
        sha512 = "JxHc1weCN68wRY0fhCoXpyK55m/XPHafOmK4UWD7m2CI14GMcFypt4w/0+NV5f/ZMby2F6S2wwA7fgynh9gWSw==";
      };
    };
    "setprototypeof-1.1.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.0.tgz";
        sha512 = "BvE/TwpZX4FXExxOxZyRGQQv651MSwmWKZGqvmPcRIjDqWub67kTKuIMx43cZZrS/cBBzwBcNDWoFxt2XEFIpQ==";
      };
    };
    "setprototypeof-1.2.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.2.0.tgz";
        sha512 = "E5LDX7Wrp85Kil5bhZv46j8jOeboKq5JMmYM3gVGdGH8xFpPWXUMsNrlODCrkoxMEeNi/XZIwuRvY4XNwYMJpw==";
      };
    };
    "snapdragon-0.8.2" = {
      name = "snapdragon";
      packageName = "snapdragon";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon/-/snapdragon-0.8.2.tgz";
        sha512 = "FtyOnWN/wCHTVXOMwvSv26d+ko5vWlIDD6zoUJ7LW8vh+ZBC8QdljveRP+crNrtBwioEUWy/4dMtbBjA4ioNlg==";
      };
    };
    "snapdragon-node-2.1.1" = {
      name = "snapdragon-node";
      packageName = "snapdragon-node";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon-node/-/snapdragon-node-2.1.1.tgz";
        sha512 = "O27l4xaMYt/RSQ5TR3vpWCAB5Kb/czIcqUFOM/C4fYcLnbZUc1PkjTAMjof2pBWaSTwOUd6qUHcFGVGj7aIwnw==";
      };
    };
    "snapdragon-util-3.0.1" = {
      name = "snapdragon-util";
      packageName = "snapdragon-util";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/snapdragon-util/-/snapdragon-util-3.0.1.tgz";
        sha512 = "mbKkMdQKsjX4BAL4bRYTj21edOf8cN7XHdYUJEe+Zn99hVEYcMvKPct1IqNe7+AZPirn8BCDOQBHQZknqmKlZQ==";
      };
    };
    "source-map-0.5.7" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.5.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.5.7.tgz";
        sha512 = "LbrmJOMUSdEVxIKvdcJzQC+nQhe8FUZQTXQy6+I75skNgn3OoQ0DZA8YnFa7gp8tqtL3KPf1kmo0R5DoApeSGQ==";
      };
    };
    "source-map-resolve-0.5.3" = {
      name = "source-map-resolve";
      packageName = "source-map-resolve";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-resolve/-/source-map-resolve-0.5.3.tgz";
        sha512 = "Htz+RnsXWk5+P2slx5Jh3Q66vhQj1Cllm0zvnaY98+NFx+Dv2CF/f5O/t8x+KaNdrdIAsruNzoh/KpialbqAnw==";
      };
    };
    "source-map-url-0.4.1" = {
      name = "source-map-url";
      packageName = "source-map-url";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map-url/-/source-map-url-0.4.1.tgz";
        sha512 = "cPiFOTLUKvJFIg4SKVScy4ilPPW6rFgMgfuZJPNoDuMs3nC1HbMUycBoJw77xFIp6z1UJQJOfx6C9GMH80DiTw==";
      };
    };
    "split-0.3.3" = {
      name = "split";
      packageName = "split";
      version = "0.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/split/-/split-0.3.3.tgz";
        sha512 = "wD2AeVmxXRBoX44wAycgjVpMhvbwdI2aZjCkvfNcH1YqHQvJVa1duWc73OyVGJUc05fhFaTZeQ/PYsrmyH0JVA==";
      };
    };
    "split-string-3.1.0" = {
      name = "split-string";
      packageName = "split-string";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/split-string/-/split-string-3.1.0.tgz";
        sha512 = "NzNVhJDYpwceVVii8/Hu6DKfD2G+NrQHlS/V/qgv763EYudVwEcMQNxd2lh+0VrUByXN/oJkl5grOhYWvQUYiw==";
      };
    };
    "static-extend-0.1.2" = {
      name = "static-extend";
      packageName = "static-extend";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/static-extend/-/static-extend-0.1.2.tgz";
        sha512 = "72E9+uLc27Mt718pMHt9VMNiAL4LMsmDbBva8mxWUCkT07fSzEGMYUCk0XWY6lp0j6RBAG4cJ3mWuZv2OE3s0g==";
      };
    };
    "statuses-1.5.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.5.0.tgz";
        sha512 = "OpZ3zP+jT1PI7I8nemJX4AKmAX070ZkYPVWV/AaKTJl+tXCTGyVdC1a4SL8RUQYEwk/f34ZX8UTykN68FwrqAA==";
      };
    };
    "statuses-2.0.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-2.0.1.tgz";
        sha512 = "RwNA9Z/7PrK06rYLIzFMlaF+l73iwpzsqRIFgbMLbTcLD6cOao82TaWefPXQvB2fOC4AjuYSEndS7N/mTCbkdQ==";
      };
    };
    "stream-combiner-0.0.4" = {
      name = "stream-combiner";
      packageName = "stream-combiner";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-combiner/-/stream-combiner-0.0.4.tgz";
        sha512 = "rT00SPnTVyRsaSz5zgSPma/aHSOic5U1prhYdRy5HS2kTZviFpmDgzilbtsJsxiroqACmayynDN/9VzIbX5DOw==";
      };
    };
    "string_decoder-1.1.1" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.1.1.tgz";
        sha512 = "n/ShnvDi6FHbbVfviro+WojiFzv+s8MPMHBczVePfUpDJLwoLT0ht1l4YwBCbi8pJAveEEdnkHyPyTP/mzRfwg==";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha512 = "w89qg7PI8wAdvX60bMDP+bFoD5Dvhm9oLheFp5O4a2QF0cSBGsBX4qZmadPMvVqlLJBBci+WqGGOAPvcDeNSVg==";
      };
    };
    "to-object-path-0.3.0" = {
      name = "to-object-path";
      packageName = "to-object-path";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-object-path/-/to-object-path-0.3.0.tgz";
        sha512 = "9mWHdnGRuh3onocaHzukyvCZhzvr6tiflAy/JRFXcJX0TjgfWA9pk9t8CMbzmBE4Jfw58pXbkngtBtqYxzNEyg==";
      };
    };
    "to-regex-3.0.2" = {
      name = "to-regex";
      packageName = "to-regex";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex/-/to-regex-3.0.2.tgz";
        sha512 = "FWtleNAtZ/Ki2qtqej2CXTOayOH9bHDQF+Q48VpWyDXjbYxA4Yz8iDB31zXOBUlOHHKidDbqGVrTUvQMPmBGBw==";
      };
    };
    "to-regex-range-2.1.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-2.1.1.tgz";
        sha512 = "ZZWNfCjUokXXDGXFpZehJIkZqq91BcULFq/Pi7M5i4JnxXdhMKAK682z8bCW3o8Hj1wuuzoKcW3DfVzaP6VuNg==";
      };
    };
    "toidentifier-1.0.1" = {
      name = "toidentifier";
      packageName = "toidentifier";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/toidentifier/-/toidentifier-1.0.1.tgz";
        sha512 = "o5sSPKEkg/DIQNmH43V0/uerLrpzVedkUh8tGNvaeXpfpuwjKenlSox/2O/BTlZUtEe+JG7s5YhEz608PlAHRA==";
      };
    };
    "union-value-1.0.1" = {
      name = "union-value";
      packageName = "union-value";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/union-value/-/union-value-1.0.1.tgz";
        sha512 = "tJfXmxMeWYnczCVs7XAEvIV7ieppALdyepWMkHkwciRpZraG/xwT+s2JN8+pr1+8jCRf80FFzvr+MpQeeoF4Xg==";
      };
    };
    "unix-crypt-td-js-1.1.4" = {
      name = "unix-crypt-td-js";
      packageName = "unix-crypt-td-js";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/unix-crypt-td-js/-/unix-crypt-td-js-1.1.4.tgz";
        sha512 = "8rMeVYWSIyccIJscb9NdCfZKSRBKYTeVnwmiRYT2ulE3qd1RaDQ0xQDP+rI3ccIWbhu/zuo5cgN8z73belNZgw==";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha512 = "pjy2bYhSsufwWlKwPc+l3cN7+wuJlK6uz0YdJEOlQDbl6jo/YlPi4mb8agUkVC8BF7V8NuzeyPNqRksA3hztKQ==";
      };
    };
    "unset-value-1.0.0" = {
      name = "unset-value";
      packageName = "unset-value";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unset-value/-/unset-value-1.0.0.tgz";
        sha512 = "PcA2tsuGSF9cnySLHTLSh2qrQiJ70mn+r+Glzxv2TWZblxsxCC52BDlZoPCsz7STd9pN7EZetkWZBAvk4cgZdQ==";
      };
    };
    "upath-1.2.0" = {
      name = "upath";
      packageName = "upath";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/upath/-/upath-1.2.0.tgz";
        sha512 = "aZwGpamFO61g3OlfT7OQCHqhGnW43ieH9WZeP7QxN/G/jS4jfqUkZxoryvJgVPEcrl5NL/ggHsSmLMHuH64Lhg==";
      };
    };
    "urix-0.1.0" = {
      name = "urix";
      packageName = "urix";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/urix/-/urix-0.1.0.tgz";
        sha512 = "Am1ousAhSLBeB9cG/7k7r2R0zj50uDRlZHPGbazid5s9rlF1F/QKYObEKSIunSjIOkJZqwRRLpvewjEkM7pSqg==";
      };
    };
    "use-3.1.1" = {
      name = "use";
      packageName = "use";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/use/-/use-3.1.1.tgz";
        sha512 = "cwESVXlO3url9YWlFW/TA9cshCEhtu7IKJ/p5soJ/gGpj7vbvFrAY/eIioQ6Dw23KjZhYgiIo8HOs1nQ2vr/oQ==";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha512 = "EPD5q1uXyFxJpCrLnCc1nHnq3gOa6DZBocAIiI2TaSCA7VCJ1UJDMagCzIkXNsUYfD1daK//LTEQ8xiIbrHtcw==";
      };
    };
    "utils-merge-1.0.1" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz";
        sha512 = "pMZTvIkT1d+TFGvDOqodOclx0QWkkgi6Tdoa8gC8ffGAAqz9pzPTZWAybbsHHoED/ztMtkv/VoYTYyShUn81hA==";
      };
    };
    "uuid-3.4.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz";
        sha512 = "HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha512 = "BNGbWLfd0eUPabhkXUVm0j8uuvREyTh5ovRa/dyow/BqAbZJyC+5fU+IzQOzmAKzYqYRAISoRhdQr3eIZ/PXqg==";
      };
    };
    "websocket-driver-0.7.4" = {
      name = "websocket-driver";
      packageName = "websocket-driver";
      version = "0.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.4.tgz";
        sha512 = "b17KeDIQVjvb0ssuSDF2cYXSg2iztliJ4B9WdsuB6J952qCPKmnVq4DyW5motImXHDC1cBT/1UezrJVsKw5zjg==";
      };
    };
    "websocket-extensions-0.1.4" = {
      name = "websocket-extensions";
      packageName = "websocket-extensions";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-extensions/-/websocket-extensions-0.1.4.tgz";
        sha512 = "OqedPIGOfsDlo31UNwYbCFMSaO9m9G/0faIHj5/dZFDMFqPTcx6UwqyOy3COEaEOg/9VsGIpdqn62W5KhoKSpg==";
      };
    };
  };
in
{
  live-server = nodeEnv.buildNodePackage {
    name = "live-server";
    packageName = "live-server";
    version = "1.2.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/live-server/-/live-server-1.2.2.tgz";
      sha512 = "t28HXLjITRGoMSrCOv4eZ88viHaBVIjKjdI5PO92Vxlu+twbk6aE0t7dVIaz6ZWkjPilYFV6OSdMYl9ybN2B4w==";
    };
    dependencies = [
      sources."accepts-1.3.8"
      (sources."anymatch-2.0.0" // {
        dependencies = [
          sources."normalize-path-2.1.1"
        ];
      })
      sources."apache-crypt-1.2.6"
      sources."apache-md5-1.1.8"
      sources."arr-diff-4.0.0"
      sources."arr-flatten-1.1.0"
      sources."arr-union-3.1.0"
      sources."array-unique-0.3.2"
      sources."assign-symbols-1.0.0"
      sources."async-each-1.0.6"
      sources."atob-2.1.2"
      (sources."base-0.11.2" // {
        dependencies = [
          sources."define-property-1.0.0"
        ];
      })
      sources."basic-auth-2.0.1"
      sources."batch-0.6.1"
      sources."bcryptjs-2.4.3"
      sources."binary-extensions-1.13.1"
      sources."bindings-1.5.0"
      (sources."braces-2.3.2" // {
        dependencies = [
          sources."extend-shallow-2.0.1"
          sources."is-extendable-0.1.1"
        ];
      })
      sources."cache-base-1.0.1"
      sources."chokidar-2.1.8"
      (sources."class-utils-0.3.6" // {
        dependencies = [
          sources."define-property-0.2.5"
          sources."is-descriptor-0.1.7"
        ];
      })
      sources."collection-visit-1.0.0"
      sources."colors-1.4.0"
      sources."component-emitter-1.3.1"
      sources."connect-3.7.0"
      sources."copy-descriptor-0.1.1"
      sources."core-util-is-1.0.3"
      sources."cors-2.8.5"
      sources."debug-2.6.9"
      sources."decode-uri-component-0.2.2"
      sources."define-property-2.0.2"
      sources."depd-2.0.0"
      sources."destroy-1.2.0"
      sources."duplexer-0.1.2"
      sources."ee-first-1.1.1"
      sources."encodeurl-1.0.2"
      sources."escape-html-1.0.3"
      sources."etag-1.8.1"
      sources."event-stream-3.3.4"
      (sources."expand-brackets-2.1.4" // {
        dependencies = [
          sources."define-property-0.2.5"
          sources."extend-shallow-2.0.1"
          sources."is-descriptor-0.1.7"
          sources."is-extendable-0.1.1"
        ];
      })
      sources."extend-shallow-3.0.2"
      (sources."extglob-2.0.4" // {
        dependencies = [
          sources."define-property-1.0.0"
          sources."extend-shallow-2.0.1"
          sources."is-extendable-0.1.1"
        ];
      })
      sources."faye-websocket-0.11.4"
      sources."file-uri-to-path-1.0.0"
      (sources."fill-range-4.0.0" // {
        dependencies = [
          sources."extend-shallow-2.0.1"
          sources."is-extendable-0.1.1"
        ];
      })
      sources."finalhandler-1.1.2"
      sources."for-in-1.0.2"
      sources."fragment-cache-0.2.1"
      sources."fresh-0.5.2"
      sources."from-0.1.7"
      sources."fsevents-1.2.13"
      sources."function-bind-1.1.2"
      sources."get-value-2.0.6"
      (sources."glob-parent-3.1.0" // {
        dependencies = [
          sources."is-glob-3.1.0"
        ];
      })
      sources."graceful-fs-4.2.11"
      sources."has-value-1.0.0"
      (sources."has-values-1.0.0" // {
        dependencies = [
          sources."kind-of-4.0.0"
        ];
      })
      sources."hasown-2.0.2"
      sources."http-auth-3.1.3"
      (sources."http-errors-2.0.0" // {
        dependencies = [
          sources."statuses-2.0.1"
        ];
      })
      sources."http-parser-js-0.5.8"
      sources."inherits-2.0.4"
      sources."is-accessor-descriptor-1.0.1"
      sources."is-binary-path-1.0.1"
      sources."is-buffer-1.1.6"
      sources."is-data-descriptor-1.0.1"
      sources."is-descriptor-1.0.3"
      sources."is-extendable-1.0.1"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      (sources."is-number-3.0.0" // {
        dependencies = [
          sources."kind-of-3.2.2"
        ];
      })
      sources."is-plain-object-2.0.4"
      sources."is-windows-1.0.2"
      sources."is-wsl-1.1.0"
      sources."isarray-1.0.0"
      sources."isobject-3.0.1"
      sources."kind-of-6.0.3"
      sources."map-cache-0.2.2"
      sources."map-stream-0.1.0"
      sources."map-visit-1.0.0"
      sources."micromatch-3.1.10"
      sources."mime-1.6.0"
      sources."mime-db-1.52.0"
      sources."mime-types-2.1.35"
      sources."mixin-deep-1.3.2"
      sources."morgan-1.10.0"
      sources."ms-2.0.0"
      sources."nan-2.20.0"
      sources."nanomatch-1.2.13"
      sources."negotiator-0.6.3"
      sources."normalize-path-3.0.0"
      sources."object-assign-4.1.1"
      (sources."object-copy-0.1.0" // {
        dependencies = [
          sources."define-property-0.2.5"
          sources."is-descriptor-0.1.7"
          sources."kind-of-3.2.2"
        ];
      })
      sources."object-visit-1.0.1"
      sources."object.pick-1.3.0"
      sources."on-finished-2.3.0"
      sources."on-headers-1.0.2"
      sources."opn-6.0.0"
      sources."parseurl-1.3.3"
      sources."pascalcase-0.1.1"
      sources."path-dirname-1.0.2"
      sources."path-is-absolute-1.0.1"
      sources."pause-stream-0.0.11"
      sources."posix-character-classes-0.1.1"
      sources."process-nextick-args-2.0.1"
      sources."proxy-middleware-0.15.0"
      sources."range-parser-1.2.1"
      sources."readable-stream-2.3.8"
      sources."readdirp-2.2.1"
      sources."regex-not-1.0.2"
      sources."remove-trailing-separator-1.1.0"
      sources."repeat-element-1.1.4"
      sources."repeat-string-1.6.1"
      sources."resolve-url-0.2.1"
      sources."ret-0.1.15"
      sources."safe-buffer-5.1.2"
      sources."safe-regex-1.1.0"
      (sources."send-0.18.0" // {
        dependencies = [
          sources."ms-2.1.3"
          sources."on-finished-2.4.1"
          sources."statuses-2.0.1"
        ];
      })
      (sources."serve-index-1.9.1" // {
        dependencies = [
          sources."depd-1.1.2"
          sources."http-errors-1.6.3"
          sources."inherits-2.0.3"
          sources."setprototypeof-1.1.0"
        ];
      })
      (sources."set-value-2.0.1" // {
        dependencies = [
          sources."extend-shallow-2.0.1"
          sources."is-extendable-0.1.1"
        ];
      })
      sources."setprototypeof-1.2.0"
      (sources."snapdragon-0.8.2" // {
        dependencies = [
          sources."define-property-0.2.5"
          sources."extend-shallow-2.0.1"
          sources."is-descriptor-0.1.7"
          sources."is-extendable-0.1.1"
        ];
      })
      (sources."snapdragon-node-2.1.1" // {
        dependencies = [
          sources."define-property-1.0.0"
        ];
      })
      (sources."snapdragon-util-3.0.1" // {
        dependencies = [
          sources."kind-of-3.2.2"
        ];
      })
      sources."source-map-0.5.7"
      sources."source-map-resolve-0.5.3"
      sources."source-map-url-0.4.1"
      sources."split-0.3.3"
      sources."split-string-3.1.0"
      (sources."static-extend-0.1.2" // {
        dependencies = [
          sources."define-property-0.2.5"
          sources."is-descriptor-0.1.7"
        ];
      })
      sources."statuses-1.5.0"
      sources."stream-combiner-0.0.4"
      sources."string_decoder-1.1.1"
      sources."through-2.3.8"
      (sources."to-object-path-0.3.0" // {
        dependencies = [
          sources."kind-of-3.2.2"
        ];
      })
      sources."to-regex-3.0.2"
      sources."to-regex-range-2.1.1"
      sources."toidentifier-1.0.1"
      (sources."union-value-1.0.1" // {
        dependencies = [
          sources."is-extendable-0.1.1"
        ];
      })
      sources."unix-crypt-td-js-1.1.4"
      sources."unpipe-1.0.0"
      (sources."unset-value-1.0.0" // {
        dependencies = [
          (sources."has-value-0.3.1" // {
            dependencies = [
              sources."isobject-2.1.0"
            ];
          })
          sources."has-values-0.1.4"
        ];
      })
      sources."upath-1.2.0"
      sources."urix-0.1.0"
      sources."use-3.1.1"
      sources."util-deprecate-1.0.2"
      sources."utils-merge-1.0.1"
      sources."uuid-3.4.0"
      sources."vary-1.1.2"
      sources."websocket-driver-0.7.4"
      sources."websocket-extensions-0.1.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "simple development http server with live reload capability";
      homepage = "https://github.com/tapio/live-server#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  uglify-js = nodeEnv.buildNodePackage {
    name = "uglify-js";
    packageName = "uglify-js";
    version = "3.18.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/uglify-js/-/uglify-js-3.18.0.tgz";
      sha512 = "SyVVbcNBCk0dzr9XL/R/ySrmYf0s372K6/hFklzgcp2lBFyXtw4I7BOdDjlLhE1aVqaI/SHWXWmYdlZxuyF38A==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "JavaScript parser, mangler/compressor and beautifier toolkit";
      homepage = "https://github.com/mishoo/UglifyJS#readme";
      license = "BSD-2-Clause";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
